# Generated by Django 4.2.5 on 2023-10-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
