# Generated by Django 4.2.5 on 2023-10-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='device',
            new_name='device_cookie',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='cookie',
        ),
    ]
