# Generated by Django 4.2.5 on 2023-10-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_rename_device_quote_device_cookie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='amount',
            new_name='price_sum',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='item',
            new_name='products_in_cart',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='email',
            new_name='user_email',
        ),
    ]
